insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("gram", "computer", 1000000,"LG", 30 ,"가벼워요")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("mugCup", "cup", 5000,"starbucks", 400 ,"물 많이들어가요")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("woodCup", "cup", 10000,"starbucks", 300 ,"자연 친화적")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("IdeaPad320", "Computer", 800000,"lonovo", 20 ,"가성비 좋아요")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("MarvelElite", "sport", 230000,"marvel", 10 ,"평범한 공")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("HyroadRush", "sport", 230000,"hyroad", 10 ,"좋은 공")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("adidasBall", "sport", 230000,"adidas", 550 ,"축구공")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("Nikejordanball", "sport", 90000,"nike", 250 ,"농구공")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("MacBook", "computer", 3200000,"apple", 70 ,"프로그래머를 위한 노트북")
insert into product(name, category, price, manufacturer, unit_In_Stock, description) values ("paperCup", "cup", 2000,"caffeebane", 100 ,"종이로만든 컵")
